# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2016)),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('styles', models.PositiveSmallIntegerField(default=1)),
                ('lowest_price_view', models.PositiveIntegerField()),
                ('detail_url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
