# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0002_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='detail_url',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='image_url',
            field=models.SlugField(max_length=200),
        ),
    ]
