# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0004_auto_20160310_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image_url',
            field=models.FilePathField(max_length=200, path='None'),
        ),
    ]
