# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0005_auto_20160310_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
