# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0006_auto_20160310_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(default='sedan', max_length=60),
        ),
    ]
