# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0008_auto_20160312_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='city_mpg',
            field=models.PositiveSmallIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='hwy_mpg',
            field=models.PositiveSmallIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='body',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV')], default='Sedan', max_length=60),
        ),
    ]
