# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0016_auto_20160315_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='range',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
