# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0018_carmodel_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='battery',
            field=models.CommaSeparatedIntegerField(blank=True, default=0, max_length=100),
        ),
    ]
