# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0019_auto_20160316_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='battery',
        ),
    ]
