# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0023_carmodel_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='power',
            field=models.CommaSeparatedIntegerField(blank=True, default=0, max_length=255),
        ),
    ]
