# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0024_auto_20160316_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='power',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
