# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0025_auto_20160316_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='torque',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
