# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0026_carmodel_torque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='motor',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='battery',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
