# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0029_carmodel_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='motor',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
