# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0031_auto_20160316_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='seats',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='version',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
