# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0037_auto_20160316_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='version',
        ),
    ]
