# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0039_carmodel_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='version',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
