# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0041_auto_20160316_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
