# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0042_auto_20160316_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='drive',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
