# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0043_carmodel_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='drive',
            field=models.CharField(choices=[('front-wheel drive', 'front wheel drive'), ('rear-wheel drive', 'rear-wheel drive'), ('all-wheel drive', 'rear-wheel drive')], default='front-wheel drive', max_length=60),
        ),
    ]
