# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0045_auto_20160405_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='body',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV')], max_length=60),
        ),
    ]
