# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0046_auto_20160405_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
