# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0047_auto_20160405_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
