# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0051_auto_20160405_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='zero_two_sixty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='styles',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
