# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterpages', '0052_auto_20160406_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='styles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='zero_two_sixty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
